"""HTML report assembly.

Single function: render_html(run_result) → str. Embeds all plots as base64
PNGs so the output file is fully self-contained (no external assets).
"""

import dataclasses
from typing import Dict, List

import numpy as np

from halflife.analysis.runner import RunResult
from halflife.analysis import plots, compatibility, transitions
from halflife.analysis.events import KIND_FUSION, KIND_FISSION


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>Composite Diagnostic — {scenario}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 1200px; margin: 1em auto; padding: 0 1em; color: #222; }}
  h1 {{ border-bottom: 2px solid #444; padding-bottom: 0.3em; }}
  h2 {{ border-bottom: 1px solid #ccc; padding-bottom: 0.2em; margin-top: 2em; }}
  .meta {{ background: #f7f7f9; padding: 0.7em 1em; border-radius: 4px; font-family: monospace; font-size: 0.9em; }}
  .stat-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.7em; margin: 1em 0; }}
  .stat {{ background: #f0f0f5; padding: 0.7em; border-radius: 4px; text-align: center; }}
  .stat .num {{ font-size: 1.5em; font-weight: bold; color: #1f77b4; }}
  .stat .label {{ font-size: 0.85em; color: #666; }}
  .full-matrix {{ max-width: 100%; max-height: 800px; overflow: scroll;
                  border: 1px solid #ccc; padding: 0.5em; margin-top: 0.5em; }}
  img {{ max-width: 100%; height: auto; }}
  footer {{ font-size: 0.85em; color: #888; margin-top: 2em; }}
</style>
</head><body>
<h1>Composite Diagnostic Report</h1>
<div class="meta">
  <strong>Scenario:</strong> {scenario}<br>
  <strong>Seed:</strong> {seed} &nbsp; <strong>Steps:</strong> {n_steps} &nbsp; <strong>Sample every:</strong> {sample_every}<br>
  <strong>Wall time:</strong> {wall:.1f}s &nbsp; <strong>Git SHA:</strong> {git_sha}<br>
  <strong>Config:</strong> num_particles={num_particles}, num_species={num_species},
   max_composite_size={max_composite_size}, max_valence={max_valence},
   use_valence={use_valence}, bond_mode={bond_mode},
   fusion_threshold={fusion_threshold}, half_life_min={half_life_min}, half_life_max={half_life_max}<br>
  <strong>Per-species valences:</strong> {valences}
</div>

<div class="stat-grid">
  <div class="stat"><div class="num">{peak_max_size}</div><div class="label">peak max size</div></div>
  <div class="stat"><div class="num">{final_max_size}</div><div class="label">final max size</div></div>
  <div class="stat"><div class="num">{mean_alive:.1f}</div><div class="label">mean alive count</div></div>
  <div class="stat"><div class="num">{degree_sat:.0%}</div><div class="label">mean degree saturation</div></div>
</div>

<h2>Tier 1 — Macroscopic time series</h2>
<img src="data:image/png;base64,{img_size_trajectory}">
<img src="data:image/png;base64,{img_size_dist}">
<img src="data:image/png;base64,{img_free_particle}">

<h2>Tier 2 — Valence / edge structure</h2>
<img src="data:image/png;base64,{img_degree_sat}">
<img src="data:image/png;base64,{img_free_bonds}">
<img src="data:image/png;base64,{img_edges_rings}">

<h2>Tier 3 — Chemical network (empirical)</h2>
<p><em>Built from {n_fusion} fusion events + {n_fission} fission events. Each
event contributes 2 cells.</em></p>
<h3>Matrix 1: Size × size mass-flow</h3>
<img src="data:image/png;base64,{img_size_bin_matrix}">
<h3>Matrix 2: Top-K composite types</h3>
<img src="data:image/png;base64,{img_top_k_matrix}">
<h3>Matrix 3: Every observed composite type</h3>
<div class="full-matrix"><img src="data:image/png;base64,{img_full_matrix}"></div>

<h2>Tier 4 — Fusion compatibility (theoretical)</h2>
<p><em>Pure chemistry — what <strong>could</strong> happen if these pairs met.
Greyed cells fail the BE threshold; cells with × markers fail the valence gate
even at structural max. Compare against Tier 3 Matrix 2 (same sort) to see
which compatible pairs never fired empirically.</em></p>
<h3>Matrix 4a: Species-pair</h3>
<img src="data:image/png;base64,{img_compat_species}">
<h3>Matrix 4b: Top-K observed-composite</h3>
<img src="data:image/png;base64,{img_compat_observed}">

<footer>
  Generated by halflife.analysis on {timestamp}.
  JAX platform: {jax_platform}.
</footer>
</body></html>
"""


def _git_sha() -> str:
    import subprocess
    try:
        return subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'],
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return "(unknown)"


def _unique_multisets_from_snapshots(snapshots, particles_species: np.ndarray = None):
    """Walk snapshots and return (hashes, multisets, total_incidence) for all unique
    composite types observed."""
    seen = {}
    incidence = {}
    for snap in snapshots:
        alive_idx = np.where(snap.alive)[0]
        for c in alive_idx:
            h = int(snap.species_hash[c])
            incidence[h] = incidence.get(h, 0) + 1
            if h not in seen:
                # Recover the multiset: snap.members[c, :n] → species via particles
                # We don't have particles species here per-snapshot. The caller passes
                # it in via the top-level config (initial state — species don't change).
                if particles_species is not None:
                    n = int(snap.member_count[c])
                    member_ids = snap.members[c, :n]
                    member_ids = member_ids[member_ids >= 0]
                    sp = tuple(sorted(int(particles_species[m]) for m in member_ids))
                    seen[h] = sp
                else:
                    seen[h] = ()
    return seen, incidence


def render_html(result: RunResult) -> str:
    """Build a single self-contained HTML string from a RunResult."""
    from halflife.state import (
        initialize_world,
        initialize_physics_params,
    )
    import datetime
    import jax

    # We need particle species for multiset reconstruction; species are constant
    # over the run, so just re-init a world with the same seed.
    init_world = initialize_world(result.config, seed=result.seed)
    particles_species = np.asarray(init_world.particles.species)
    physics = initialize_physics_params(result.config)

    # Tier 1, 2 plots.
    img_size_trajectory = plots.plot_size_trajectory(result.per_step_metrics)
    img_size_dist       = plots.plot_size_distribution_heatmap(result.per_step_metrics)
    img_free_particle   = plots.plot_free_particle_fraction(result.per_step_metrics)
    img_degree_sat      = plots.plot_degree_saturation(result.per_step_metrics)
    img_free_bonds      = plots.plot_free_bonds_heatmap(result.per_step_metrics)
    img_edges_rings     = plots.plot_edge_and_ring_counts(result.per_step_metrics)

    # Tier 3 matrices.
    M_size_bin = transitions.size_bin_transition_matrix(
        result.events, result.config.max_composite_size
    )
    M_top_k, top_k_labels = transitions.top_k_transition_matrix(result.events, K=30)
    M_full, full_labels = transitions.full_transition_matrix(result.events)

    img_size_bin_matrix = plots.plot_transition_matrix(
        M_size_bin, title='Matrix 1: Size-class transitions (rows=source, cols=product)',
    )
    img_top_k_matrix = plots.plot_transition_matrix(
        M_top_k, labels=top_k_labels, title='Matrix 2: Top-K composite-type transitions',
    )
    img_full_matrix = plots.plot_transition_matrix(
        M_full, labels=None,  # too many to show
        title=f'Matrix 3: All {len(full_labels)} observed composite types',
    )

    # Tier 4 compatibility matrices.
    be_a, pbe_a, pval_a = compatibility.species_pair_compat_matrix(result.config, physics)
    img_compat_species = plots.plot_compatibility_matrix(
        be_a, pbe_a, pval_a,
        title='Matrix 4a: Species-pair fusion compatibility',
        labels=[f's{i}' for i in range(result.config.num_species)],
    )

    # For Matrix 4b, build the same top-K hash list used by Matrix 2 (sorted by size).
    # Reconstruct multisets by re-walking incidence + snapshots.
    seen, incidence = _unique_multisets_from_snapshots(result.snapshots, particles_species)
    if seen:
        # Pick top-K by incidence then sort by size,hash for stable display.
        from collections import Counter
        top_hashes = [h for h, _ in Counter(incidence).most_common(30)]
        top_hashes.sort(key=lambda h: (len(seen.get(h, ())), h))
        top_multisets = [seen.get(h, ()) for h in top_hashes]
        top_hashes_arr = np.array(top_hashes, dtype=np.uint32)
        be_b, pbe_b, pval_b = compatibility.observed_pair_compat_matrix(
            top_hashes_arr, top_multisets, result.config, physics,
        )
        img_compat_observed = plots.plot_compatibility_matrix(
            be_b, pbe_b, pval_b,
            title='Matrix 4b: Top-K observed-composite compatibility',
            labels=[f"0x{h:08x}" for h in top_hashes],
        )
    else:
        # No composites ever formed — render a 1x1 placeholder.
        img_compat_observed = plots.plot_compatibility_matrix(
            np.zeros((1, 1)), np.zeros((1, 1), bool), np.ones((1, 1), bool),
            title='Matrix 4b: (no observed composites)',
        )

    # Headline derived numbers.
    peak_max_size  = int(result.per_step_metrics['max_size'].max())
    final_max_size = int(result.per_step_metrics['max_size'][-1])
    mean_alive     = float(result.per_step_metrics['alive_count'].mean())
    degree_sat     = float(result.per_step_metrics['degree_saturation_pct'].mean())

    n_fusion  = int((result.events.kind == KIND_FUSION).sum())
    n_fission = int((result.events.kind == KIND_FISSION).sum())

    return _HTML_TEMPLATE.format(
        scenario=getattr(result.config, '_scenario_name', '(custom)'),
        seed=result.seed,
        n_steps=result.n_steps,
        sample_every=result.sample_every,
        wall=result.wall_seconds,
        git_sha=_git_sha(),
        num_particles=result.config.num_particles,
        num_species=result.config.num_species,
        max_composite_size=result.config.max_composite_size,
        max_valence=result.config.max_valence,
        use_valence=result.config.use_valence,
        bond_mode=getattr(result.config, 'bond_mode', '(n/a)'),
        fusion_threshold=physics.fusion_threshold,
        half_life_min=result.config.half_life_min,
        half_life_max=result.config.half_life_max,
        valences=result.species_values.tolist(),
        peak_max_size=peak_max_size,
        final_max_size=final_max_size,
        mean_alive=mean_alive,
        degree_sat=degree_sat,
        img_size_trajectory=img_size_trajectory,
        img_size_dist=img_size_dist,
        img_free_particle=img_free_particle,
        img_degree_sat=img_degree_sat,
        img_free_bonds=img_free_bonds,
        img_edges_rings=img_edges_rings,
        img_size_bin_matrix=img_size_bin_matrix,
        img_top_k_matrix=img_top_k_matrix,
        img_full_matrix=img_full_matrix,
        img_compat_species=img_compat_species,
        img_compat_observed=img_compat_observed,
        n_fusion=n_fusion, n_fission=n_fission,
        jax_platform=jax.default_backend(),
        timestamp=datetime.datetime.now().isoformat(timespec='seconds'),
    )
